language: python
python:
  - "3.6"
  - "3.7-dev"

services:
  - postgresql

install:
  - pip install -e .
  - pip install -r requirements.testing.txt --upgrade
  - source ./set_environment_variables.sh

script:
  - py.test -s -v --cov-report xml --cov=graphvl tests/
  - codecov
