apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphvl
spec:
  selector:
    matchLabels:
      app: graphvl
  replicas: 3
  template:
    metadata:
      labels:
        app: graphvl
    spec:
      containers:
        - name: graphvl
          image: graphvl:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
